name: Publish to npm


on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      
      - name: install dev deps
        run: npm ci

      - name: Publish to npm
        run: npm publish --provenance --access public

